separate checks to prevent installing docker if requirements aren't even met

diff --git a/.github/workflows/build-cv.yml b/.github/workflows/build-cv.yml
--- a/.github/workflows/build-cv.yml
+++ b/.github/workflows/build-cv.yml
@@ -12,30 +12,38 @@ on:
   pull_request:
 
 jobs:
+  verify-requirements:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Verify LaTeX preamble
+        run: |  
+          test -f mysetup.tex || (echo "ERROR: MySetup.tex missing" && exit 1)
+
+      - name: Verify LaTeX vars
+        run: |  
+          test -f vars.tex || (echo "ERROR: vars.tex missing" && exit 1)
+
+      - name: Verify LaTeX cv
+        run: |  
+          test -f cv.tex || (echo "ERROR: cv.tex missing" && exit 1)
+
+      - name: Verify Makefile
+        run: |  
+          test -f makefile || (echo "ERROR: makefile missing" && exit 1)
+
   build-pdf:
     runs-on: ubuntu-latest
+    needs: verify-requirments
+
     container:
       image: texlive/texlive:latest
 
     steps:
     - name: Checkout repository
       uses: actions/checkout@v4
-
-    - name: Verify LaTeX preamble
-      run: |  
-        test -f mysetup.tex || (echo "ERROR: MySetup.tex missing" && exit 1)
-
-    - name: Verify LaTeX vars
-      run: |  
-        test -f vars.tex || (echo "ERROR: vars.tex missing" && exit 1)
-
-    - name: Verify LaTeX cv
-      run: |  
-        test -f cv.tex || (echo "ERROR: cv.tex missing" && exit 1)
-
-    - name: Verify Makefile
-      run: |  
-        test -f makefile || (echo "ERROR: makefile missing" && exit 1)
 
     - name: Build CV with latexmk
       run: |
